name: Order Processing

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update_and_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth python-dotenv pandas numpy
      
      - name: Run script
        env:
          ENCODED_CREDENTIALS: ${{ secrets.ENCODED_CREDENTIALS }}
          ORDERS_SHEET_ID: ${{ secrets.ORDERS_SHEET_ID }}
          DISCOUNTS_SHEET_ID: ${{ secrets.DISCOUNTS_SHEET_ID }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
          PORT: ${{ secrets.PORT }}
        run: python order_confirmation.py
